import { StyleSheet } from "react-native";

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 16,
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 16,
  },
  subtitle: {
    fontSize: 20,
    marginTop: 4,
    color: "#666",
    textAlign: 'center',
    marginBottom: 16,
  },
  input: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#ddd",
    fontSize: 18,
    marginTop: 16,
    backgroundColor: '#fff',
  },
  buttonContainer: {
    backgroundColor: "lightgreen",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignSelf: "flex-end",
    alignItems: "center",
    marginTop: 8,
  },
  buttonText: {
    fontSize: 18,
    color: "#fff",
    fontWeight: 'bold',
  },
  deleteButtonContainer: {
    backgroundColor: "red",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignSelf: "flex-start",
    alignItems: "center",
    marginTop: 8,
  },
  deleteButtonText: {
    fontSize: 18,
    color: "white",
  },
  divider: {
    height: 1,
    backgroundColor: "#ddd",
    marginVertical: 32,
  },
  taskContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#ddd",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#fff',
    marginBottom: 8,
  },
  taskText: {
    fontSize: 18,
    flex: 1,
  },
  taskDate: {
    fontSize: 16,
    color: "#888",
    marginLeft: 8,
  },
  taskPriority: {
    fontSize: 16,
    color: "#888",
    marginLeft: 8,
  },
  taskDelete: {
    width: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  taskDeleteText: {
    fontSize: 18,
    color: "white",
  },
});
